// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgkpmaavlhhijhqknmsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNna3BtYWF2bGhoaWpocWtubXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTc4NDEsImV4cCI6MjA2ODk5Mzg0MX0.ukp-GddEyeNkPrSkb-qSIfCHnczsO-hh5h4wgvuLru0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});